### PR TITLE
ARM: dts: msm8974-bacon: Add backlight support

### PR DESCRIPTION
**Pull request by valentino-sm**
The party right here:
/sys/devices/platform/soc/f9924000.i2c/i2c-1/1-0036/backlight/lcd-backlight

### CODE REVIEW

**Comment by minlexx** [comment]
Since the commits from this repo will eventually be going to main linux repo, they should be signed as required by upstream.

See https://github.com/msm8916-mainline/linux/blob/master/CONTRIBUTING.md , rules for this repo should be almost the same

**Comment by z3ntu** [comment]
@valentino-sm Any update here?

**Comment by minlexx** [comment]
All we need is really only the `Signed-off-by: Your name <your@email>` line and we can get this in.

We can't accept anonymous contributions that are going to linux kernel..

**Comment by z3ntu** [comment]
This is now supported since https://lore.kernel.org/linux-arm-msm/20230122-msm8974-bacon-features-v1-4-4049f565c24c@z3ntu.xyz/

**Pull request closed without merging**
