### PR TITLE
ARM: dts: msm8974-bacon: Add support for hardware buttons

### PR DESCRIPTION
**Pull request by valentino-sm**

### CODE REVIEW

**Comment by Kaned1as** [comment]
Aren't PmOS repositories hosted on Gitlab?

**Comment by valentino-sm** [comment]
> Aren't PmOS repositories hosted on Gitlab?

They are, but msm8974 stay here for some unknown reason.

I'm ashamed of this commit.
I don't know how to clear power-on section properly.
gpio-keys would be better than gpio_keys

**Comment by minlexx** [comment]
> Aren't PmOS repositories hosted on Gitlab?

This is the correct place to send MRs to 8974 kernel now. See https://gitlab.com/postmarketOS/postmarketos/-/issues/47

**Comment by minlexx** [comment]
> I'm ashamed of this commit. I don't know how to clear power-on section properly. gpio-keys would be better than gpio_keys

Yeah, there are few problems with this commit. What I can say for now is:
1) add Signed-off-by line, proper commit description
2) see example in other devices dts (fp2 or hammerhead) on how to write gpio-keys and pmic nodes

**Comment by Kaned1as** [comment]
> I'm ashamed of this commit.
> I don't know how to clear power-on section properly.
> gpio-keys would be better than gpio_keys

image

Id's say it looks okay, just needs a little cleanup. Device tree specification has some nice overview of aliases and extensions. Proper commit messages are important because PmOS guys are diligent and tend to send these patches to upstream linux, this clears a lot of questions.

**Comment by minlexx** [comment]
@Kaned1as will you be able to test changes on oneplus-bacon?

**Comment by Kaned1as** [comment]
> @Kaned1as will you be able to test changes on oneplus-bacon?

nope, I'm sorry, had to leave Russia.
I'll be buying it from the first 2nd hand I encounter once I settle though.

**Comment by z3ntu** [comment]
@valentino-sm Any update here?

**Comment by z3ntu** [comment]
Volume keys (and hall sensor) are now supported with https://lore.kernel.org/linux-arm-msm/20230122-msm8974-bacon-features-v1-3-4049f565c24c@z3ntu.xyz/

**Pull request closed without merging**
